[server]
headless = true
enableCORS = false

[theme]
primaryColor = "#B22234"  # Red
backgroundColor = "#FFFFFF"  # White
secondaryBackgroundColor = "#3C3B6E"  # Blue
textColor = "#000000"  # Black
font = "times new roman"